name: random_user_fetcher
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: ^3.5.4

dependencies:

  http: ^0.13.5 

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
